AllCops:
  DisabledByDefault: false
  NewCops: enable

Style/HashSyntax:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
  EnforcedStyle: always

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 180

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Exclude:
    - 'algolia.gemspec'

Gemspec/RequiredRubyVersion:
  Exclude:
    - 'algolia.gemspec'

Lint/DuplicateMethods:
  Enabled: false

Lint/SymbolConversion:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Metrics/BlockNesting:
  Max: 4

Metrics/ParameterLists:
  Max: 7

Security/CompoundHash:
  Enabled: false
