module Algolia
  class AddApiKeyResponse < BaseResponse
    attr_reader raw_response: Hash[Symbol, String|[String]]

    # TODO add client
    def initialize: (untyped client, Hash[Symbol, String|[String]] response) -> bool
    def wait: (?::Hash[Symbol, String|[String]] opts) -> self
  end
end
