module Algolia
  class RestoreApiKeyResponse < BaseResponse
    attr_reader raw_response: Hash[Symbol, String|[String]]

    def initialize: (Algolia::Search::Client client, String key) -> bool
    def wait: (?::Hash[Symbol, String|[String]] opts) -> self
  end
end
