# frozen_string_literal: true

# Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

require "date"
require "time"

module Algolia
  module AgentStudio
    class CompatibilityMode
      AI_SDK_4 = "ai-sdk-4".freeze
      AI_SDK_5 = "ai-sdk-5".freeze

      def self.all_vars
        @all_vars ||= [AI_SDK_4, AI_SDK_5].freeze
      end

      # Builds the enum from string
      # @param [String] The enum value in the form of the string
      # @return [String] The enum value
      def self.build_from_hash(value)
        new.build_from_hash(value)
      end

      # Builds the enum from string
      # @param [String] The enum value in the form of the string
      # @return [String] The enum value
      def build_from_hash(value)
        return value if CompatibilityMode.all_vars.include?(value)
        raise "Invalid ENUM value #{value} for class #CompatibilityMode"
      end
    end
  end
end
