# frozen_string_literal: true

# Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

require "date"
require "time"

module Algolia
  module AgentStudio
    # Universal storage model for all memory types (semantic, episodic).  This is the ONLY model that touches storage (Algolia). Domain models (SemanticMemory, EpisodicMemory) are used for LLM extraction and converted to MemoryRecord before saving.  See https://langchain-ai.github.io/langmem/concepts/conceptual_guide/#memory-types for memory type definitions.
    class MemoryRecord
      attr_accessor :memory_type

      attr_accessor :episode

      # Self-contained, first-person memory for long-term recall.
      attr_accessor :text

      # Verbatim conversation extract, not paraphrased.
      attr_accessor :raw_extract

      # 5-20 free-form keywords: entities, context, search terms (any words).
      attr_accessor :keywords

      # 2-4 topics ONLY from this list: [complaints, entertainment, family, feedback, finance, food, goals, health, history, hobbies, learning, praise, preferences, schedule, shopping, technical, travel, work].
      attr_accessor :topics

      # Arbitrary labels/themes for flexible categorization (e.g., 'Q1-goals', 'paris-trip', 'vip-customer').
      attr_accessor :_tags

      # 3-5 natural phrases that should trigger this memory.
      attr_accessor :recall_triggers

      # ObjectID of existing memory to update. Leave empty for new memory.
      attr_accessor :algolia_object_id

      # Application ID.
      attr_accessor :app_id

      # Agent IDs with access: ['agent1'], ['*'] for all, ['*', '-agent1'] to exclude.
      attr_accessor :agent_ids

      # User ID.
      attr_accessor :user_id

      # Epoch seconds.
      attr_accessor :created_at

      # Epoch seconds.
      attr_accessor :updated_at

      # Attribute mapping from ruby-style variable name to JSON key.
      def self.attribute_map
        {
          :memory_type => :memoryType,
          :episode => :episode,
          :text => :text,
          :raw_extract => :rawExtract,
          :keywords => :keywords,
          :topics => :topics,
          :_tags => :_tags,
          :recall_triggers => :recallTriggers,
          :algolia_object_id => :objectID,
          :app_id => :appId,
          :agent_ids => :agentIDs,
          :user_id => :userID,
          :created_at => :createdAt,
          :updated_at => :updatedAt
        }
      end

      # Attribute type mapping.
      def self.types_mapping
        {
          :memory_type => :"MemoryType",
          :episode => :"Episode",
          :text => :"String",
          :raw_extract => :"String",
          :keywords => :"Array<String>",
          :topics => :"Array<String>",
          :_tags => :"Array<String>",
          :recall_triggers => :"Array<String>",
          :algolia_object_id => :"String",
          :app_id => :"String",
          :agent_ids => :"Array<String>",
          :user_id => :"String",
          :created_at => :"Integer",
          :updated_at => :"Integer"
        }
      end

      # List of attributes with nullable: true
      def self.openapi_nullable
        Set.new(
          [
            :episode,
            :algolia_object_id
          ]
        )
      end

      # Initializes the object
      # @param [Hash] attributes Model attributes in the form of hash
      def initialize(attributes = {})
        if (!attributes.is_a?(Hash))
          raise(
            ArgumentError,
            "The input argument (attributes) must be a hash in `Algolia::MemoryRecord` initialize method"
          )
        end

        # check to see if the attribute exists and convert string to symbol for hash key
        attributes = attributes.each_with_object({}) { |(k, v), h|
          if (!self.class.attribute_map.key?(k.to_sym))
            raise(
              ArgumentError,
              "`#{k}` is not a valid attribute in `Algolia::MemoryRecord`. Please check the name to make sure it's valid. List of attributes: " +
                self.class.attribute_map.keys.inspect
            )
          end

          h[k.to_sym] = v
        }

        if attributes.key?(:memory_type)
          self.memory_type = attributes[:memory_type]
        end

        if attributes.key?(:episode)
          self.episode = attributes[:episode]
        end

        if attributes.key?(:text)
          self.text = attributes[:text]
        else
          self.text = nil
        end

        if attributes.key?(:raw_extract)
          self.raw_extract = attributes[:raw_extract]
        else
          self.raw_extract = nil
        end

        if attributes.key?(:keywords)
          if (value = attributes[:keywords]).is_a?(Array)
            self.keywords = value
          end
        end

        if attributes.key?(:topics)
          if (value = attributes[:topics]).is_a?(Array)
            self.topics = value
          end
        end

        if attributes.key?(:_tags)
          if (value = attributes[:_tags]).is_a?(Array)
            self._tags = value
          end
        end

        if attributes.key?(:recall_triggers)
          if (value = attributes[:recall_triggers]).is_a?(Array)
            self.recall_triggers = value
          end
        end

        if attributes.key?(:algolia_object_id)
          self.algolia_object_id = attributes[:algolia_object_id]
        end

        if attributes.key?(:app_id)
          self.app_id = attributes[:app_id]
        end

        if attributes.key?(:agent_ids)
          if (value = attributes[:agent_ids]).is_a?(Array)
            self.agent_ids = value
          end
        end

        if attributes.key?(:user_id)
          self.user_id = attributes[:user_id]
        end

        if attributes.key?(:created_at)
          self.created_at = attributes[:created_at]
        end

        if attributes.key?(:updated_at)
          self.updated_at = attributes[:updated_at]
        end
      end

      # Checks equality by comparing each attribute.
      # @param [Object] Object to be compared
      def ==(other)
        return true if self.equal?(other)
        self.class == other.class &&
          memory_type == other.memory_type &&
          episode == other.episode &&
          text == other.text &&
          raw_extract == other.raw_extract &&
          keywords == other.keywords &&
          topics == other.topics &&
          _tags == other._tags &&
          recall_triggers == other.recall_triggers &&
          algolia_object_id == other.algolia_object_id &&
          app_id == other.app_id &&
          agent_ids == other.agent_ids &&
          user_id == other.user_id &&
          created_at == other.created_at &&
          updated_at == other.updated_at
      end

      # @see the `==` method
      # @param [Object] Object to be compared
      def eql?(other)
        self == other
      end

      # Calculates hash code according to all attributes.
      # @return [Integer] Hash code
      def hash
        [
          memory_type,
          episode,
          text,
          raw_extract,
          keywords,
          topics,
          _tags,
          recall_triggers,
          algolia_object_id,
          app_id,
          agent_ids,
          user_id,
          created_at,
          updated_at
        ].hash
      end

      # Builds the object from hash
      # @param [Hash] attributes Model attributes in the form of hash
      # @return [Object] Returns the model itself
      def self.build_from_hash(attributes)
        return nil unless attributes.is_a?(Hash)
        attributes = attributes.transform_keys(&:to_sym)
        transformed_hash = {}
        types_mapping.each_pair do |key, type|
          if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
            transformed_hash[key.to_sym] = nil
          elsif type =~ /\AArray<(.*)>/i
            # check to ensure the input is an array given that the attribute
            # is documented as an array but the input is not
            if attributes[attribute_map[key]].is_a?(Array)
              transformed_hash[key.to_sym] = attributes[attribute_map[key]].map { |v|
                _deserialize(::Regexp.last_match(1), v)
              }
            end
          elsif !attributes[attribute_map[key]].nil?
            transformed_hash[key.to_sym] = _deserialize(type, attributes[attribute_map[key]])
          end
        end

        new(transformed_hash)
      end

      # Deserializes the data based on type
      # @param string type Data type
      # @param string value Value to be deserialized
      # @return [Object] Deserialized data
      def self._deserialize(type, value)
        case type.to_sym
        when :Time
          Time.parse(value)
        when :Date
          Date.parse(value)
        when :String
          value.to_s
        when :Integer
          value.to_i
        when :Float
          value.to_f
        when :Boolean
          if value.to_s =~ /\A(true|t|yes|y|1)\z/i
            true
          else
            false
          end

        when :Object
          # generic object (usually a Hash), return directly
          value
        when /\AArray<(?<inner_type>.+)>\z/
          inner_type = Regexp.last_match[:inner_type]
          value.map { |v| _deserialize(inner_type, v) }
        when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
          k_type = Regexp.last_match[:k_type]
          v_type = Regexp.last_match[:v_type]
          {}.tap do |hash|
            value.each do |k, v|
              hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
            end
          end
          # model
        else
          # models (e.g. Pet) or oneOf
          klass = Algolia::AgentStudio.const_get(type)
          klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass
            .build_from_hash(value)
        end
      end

      # Returns the string representation of the object
      # @return [String] String presentation of the object
      def to_s
        to_hash.to_s
      end

      # to_body is an alias to to_hash (backward compatibility)
      # @return [Hash] Returns the object in the form of hash
      def to_body
        to_hash
      end

      def to_json(*_args)
        to_hash.to_json
      end

      # Returns the object in the form of hash
      # @return [Hash] Returns the object in the form of hash
      def to_hash
        hash = {}
        self.class.attribute_map.each_pair do |attr, param|
          value = send(attr)
          if value.nil?
            is_nullable = self.class.openapi_nullable.include?(attr)
            next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
          end

          hash[param] = _to_hash(value)
        end

        hash
      end

      # Outputs non-array value in the form of hash
      # For object, use to_hash. Otherwise, just return the value
      # @param [Object] value Any valid value
      # @return [Hash] Returns the value in the form of hash
      def _to_hash(value)
        if value.is_a?(Array)
          value.map { |v| _to_hash(v) }
        elsif value.is_a?(Hash)
          {}.tap do |hash|
            value.each { |k, v| hash[k] = _to_hash(v) }
          end
        elsif value.respond_to?(:to_hash)
          value.to_hash
        else
          value
        end
      end
    end
  end
end
