module Algolia
  module Search
    class Config < BaseConfig
      include CallType

      attr_accessor default_hosts: [Hash[Symbol, String|[String]]]

      def initialize: (?::Hash[Symbol, String|[String]] opts) -> void
    end
  end
end
