module Algolia
  module Transport
    class StatefulHost
      include CallType

      attr_reader url: String
      attr_reader protocol: String
      attr_reader accept: String
      attr_accessor last_use: Time
      attr_accessor retry_count: Integer
      attr_accessor up: bool

      def initialize: (String url, ?::Hash[Symbol|String, untyped] opts) -> void
    end
  end
end
