module Algolia
  module Transport
    # Class StatefulHost
    class StatefulHost
      include CallType

      attr_reader url: untyped

      attr_reader protocol: untyped

      attr_reader accept: untyped

      attr_accessor last_use: untyped

      attr_accessor retry_count: untyped

      attr_accessor up: untyped

      #
      # @param url [String] host url
      # @option options [binary] :accept accept type flag
      # @option options [DateTime] :last_use last usage date
      # @option options [Integer] :retry_count number of retries
      # @option options [Boolean] :up host status
      #
      def initialize: (untyped url, ?::Hash[untyped, untyped] opts) -> untyped
    end
  end
end
