module Algolia
  class BaseIterator
    include Helpers
    #TODO: double check Enumerable
    include Enumerable[Hash[Symbol, String|[String]], void]

    attr_reader transporter: Algolia::Transport::Transport
    attr_reader index_name: String
    attr_reader opts: Hash[Symbol, String|[String]]

    def initialize: (Algolia::Transport::Transport transporter, String index_name, Hash[Symbol, String|[String]] opts) -> void
  end
end
