module Algolia
  class ObjectIterator < BaseIterator
    # Custom each function to iterate through the objects
    #
    def each: () { (Hash[Symbol, String|[String]]) -> void } -> Hash[Symbol, String|[String]]
  end
end
