# Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

require 'date'
require 'time'

module Algolia
  module Search
    class SynonymType
      SYNONYM = "synonym".freeze
      ONEWAYSYNONYM = "onewaysynonym".freeze
      ALTCORRECTION1 = "altcorrection1".freeze
      ALTCORRECTION2 = "altcorrection2".freeze
      PLACEHOLDER = "placeholder".freeze

      def self.all_vars
        @all_vars ||= [SYNONYM, ONEWAYSYNONYM, ALTCORRECTION1, ALTCORRECTION2, PLACEHOLDER].freeze
      end

      # Builds the enum from string
      # @param [String] The enum value in the form of the string
      # @return [String] The enum value
      def self.build_from_hash(value)
        new.build_from_hash(value)
      end

      # Builds the enum from string
      # @param [String] The enum value in the form of the string
      # @return [String] The enum value
      def build_from_hash(value)
        return value if SynonymType.all_vars.include?(value)
        raise "Invalid ENUM value #{value} for class #SynonymType"
      end
    end
  end
end
